name: CI
on: [push, pull_request]
jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1

    - name: Install container dependencies
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Cache application dependencies
      uses: actions/cache@v1
      working-directory: ${{ env.working-directory }}
      env:
        cache-name: cache-requirements
      with:
        path: ~/.requirements
        key: ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-ci-${{ env.cache-name }}

    - name: Install application dependencies
      working-directory: ${{ env.working-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint
      working-directory: ${{ env.working-directory }}
      run: flake8 --exclude migrations config app

    - name: Test
      working-directory: ${{ env.working-directory }}
      run: python manage.py test
      env:
        SECRET_KEY: 'ci'
        ALLOWED_HOSTS: '*'
        DEBUG: 'True'
        DEFAULT_CACHE_BACKEND: 'dummy'
