name: CI
on: [push, pull_request]
jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1

    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint
      working-directory: ${{env.working-directory}}
      run: flake8 config app

    - name: Test
      working-directory: ${{env.working-directory}}
      run: python manage.py test
