name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          source .bash_profile
          cd /home/megahack/multiplicae
          git pull
          cd /home/megahack/multiplicae/backend
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build --no-deps --d
          cd /home/megahack/multiplicae/frontend
          npm install
          npm run build
          npm run deploy

