name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          source .bash_profile
          cd /home/megahack/megahack
          git pull
          cd /home/megahack/megahack/backend
          docker-compose build
          docker-compose restart dramatiq web
          cd /home/megahack/megahack/frontend
          npm install
          npm run build
          echo ${{ secrets.password }} | sudo npm run postbuild
